app/uk/gov/hmrc/nisp/views/account.scala.html
app/uk/gov/hmrc/nisp/views/excluded.scala.html
app/uk/gov/hmrc/nisp/views/main.scala.html
app/uk/gov/hmrc/nisp/views/nispMain.scala.html
project/FrontendBuild.scala

* The dimension code has been changed to ```set``` rather than send a ```send pageview```
* The analytics code is now sent to play-ui so we no longer have to handle the submission see https://github.com/hmrc/play-ui/blob/master/src/main/twirl/uk/gov/hmrc/play/views/layouts/footer.scala.html

NISP-1603: Fix GA pageview event duplication

---

app/uk/gov/hmrc/nisp/views/exclusions/isleOfMan.scala.html
app/uk/gov/hmrc/nisp/views/exclusions/overseas.scala.html
conf/messages

@swatcats143 and @InduTest - I have added a link to contact the FPC on the IOM and Overseas exclusion messages. Also a minor text change on the second paragraph of the Overseas exclusion.

NISP-1621: Add link to contact FPC exclusion messages

---

app/uk/gov/hmrc/nisp/assets/sass/_nirecord.scss

Adjusted width percentages, so it works even in Iphone 6 landscape! Also tested with desktop browsers and other mobile devices.

NISP-1620 Fixed issue with Iphone 6 landscape view of NI record page

---

conf/messages

@swatcats143 and @InduTest - the link on this page doesn't need an 'opens in new tab' comment. Steven says it's okay to keep the rel=external but to change the phrase to Future Pension Centre.

NISP-1668: Change link on age eligibility page

---

app/uk/gov/hmrc/nisp/connectors/NispConnector.scala
app/uk/gov/hmrc/nisp/controllers/AccountController.scala
app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala
app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala
app/uk/gov/hmrc/nisp/events/AccountExclusionEvent.scala
app/uk/gov/hmrc/nisp/models/ExclusionsModel.scala
app/uk/gov/hmrc/nisp/models/NIResponse.scala
app/uk/gov/hmrc/nisp/models/NISummary.scala
app/uk/gov/hmrc/nisp/models/SPResponseModel.scala
app/uk/gov/hmrc/nisp/models/enums/Exclusion.scala
app/uk/gov/hmrc/nisp/services/MetricsService.scala
app/uk/gov/hmrc/nisp/views/excluded.scala.html
test/resources/contractedout/nirecord.json
test/resources/excluded/nirecord.json
test/resources/excluded/summary.json
test/resources/forecastonly/nirecord.json
test/resources/fulluser/nirecord.json
test/resources/mqp/nirecord.json
test/resources/regular/nirecord.json
test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala
test/uk/gov/hmrc/nisp/helpers/MockMetricsService.scala
test/uk/gov/hmrc/nisp/models/enums/SPExclusionSpec.scala

* Added Exclusions to `NIResponse` to match Backend
* Added `isAbroad` to `NIReponse.NISummary` to match Backend
Still needs Exclusions for NI Record page implemented and Unit Tests for them.
Backend: https://github.com/hmrc/nisp/pull/22
FOR REVIEW ONLY DO NOT MERGE

NISP-1732: Add Exclusions and isAbroad to NI

---

app/uk/gov/hmrc/nisp/views/exclusions/sp/isleOfMan.scala.html

@InduTest and @swatcats143 - I have added an extra sentence to the current IOM exclusion message (from State Pension start page), so that customers can contact the NI helpine should they want more details about their NI record.

NISP-1563: Add contact NI helpline message to IOM exclusion

---

conf/messages

@InduTest - I have changed the **nisp.excluded.contactFuturePensionCentre** message which will affect the other exclusion messages.

NISP-1834: Add the peer-reviewed dissonance exclusion message

---

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss

A simple hack to increase the width of the account page to 66.666% . I reviewed the other pages it appears they don't need to be increased to 66%, therefore only the account page has been increased.

NISP-1816 Overriding style to increase account page width to 66.666%

---

app/uk/gov/hmrc/nisp/views/account.scala.html
app/uk/gov/hmrc/nisp/views/account_cope.scala.html
app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html
app/uk/gov/hmrc/nisp/views/account_mqp.scala.html
app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html
app/uk/gov/hmrc/nisp/views/finalPage.scala.html
app/uk/gov/hmrc/nisp/views/includes/continueWorking.scala.html
app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html
app/uk/gov/hmrc/nisp/views/includes/reached.scala.html
app/uk/gov/hmrc/nisp/views/iv/failurepages/technical_issue.scala.html
app/uk/gov/hmrc/nisp/views/iv/failurepages/timeout.scala.html
app/uk/gov/hmrc/nisp/views/landing.scala.html
app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html
conf/messages
test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala

@InduTest - I've changed most of the apostrophes to smart ones using &rsquo; but some I've had to copy in the ’ instead.
@dspork - I've run sbt compile and sbt test (correcting any errors) so it should all be good.

NISP 1898: Smart apostrophes

---

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html

* Adds the current year is not available to the gaps page mimicking the full record
* This does not apply when the current year is posted.

NISP-1887: Add "year is not available" to gaps page

---

conf/messages

@InduTest - I've added the missing April to the scenarios that will reach their personal maximum before SPA
@dspork - two words added, so I'm not sure what other checking is required.

NISP-1927: Add the missing April

---

conf/messages

@dspork - I've just changed those two references, so everything else should be fine.
@swaistle and @InduTest - two words have changed, which I hope won't muck up any tests.

NISP-1981: Change T&C page - should be Check your State Pension

---

conf/messages

@dspork - only changed the messages file, so should be okay
@InduTest and @swaistle - changing reference from gaps to years (only on the main page), not including the URL link phrase.

NISP-2011: Replace reference from gaps to years (only on the main page)

---

app/uk/gov/hmrc/nisp/views/account.scala.html
app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html
app/uk/gov/hmrc/nisp/views/includes/continueWorking.scala.html
app/uk/gov/hmrc/nisp/views/includes/reached.scala.html
conf/messages

...except when referencing 'today amount'
@dspork - I have only revised {{nisp.main.estimate}} to {{{nisp.main.caveat}}, as we already have {{nisp.main.forecast}} and it would have looked odd in the code.
@InduTest and @swaistle - all done ready for testing

NISP-2012: Replace estimate with forecast

---

app/uk/gov/hmrc/nisp/views/account_mqp.scala.html

There were three compile warnings because of incomplete match statements in the `account_mqp` view. This request replaces the problematic statements with `if` statements as well as tabbing adjustments.

Fix sbt:compile warnings about incomplete matches

---

app/uk/gov/hmrc/nisp/controllers/QuestionnaireController.scala
app/uk/gov/hmrc/nisp/views/includes/questionnaireForm.scala.html
project/FrontendBuild.scala

This PR adds the ideal fix for NISP-2007 - the underlying issue was that play-ui error summary did not accept message arguments.
I raised an [issue](https://github.com/hmrc/play-ui/issues/53) for this and subsequently [fixed it](https://github.com/hmrc/play-ui/pull/54).
I've upgraded play-ui to reflect the new changes and removed the workaround.

Remove survey workaround | play-ui upgrade

---

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala
app/uk/gov/hmrc/nisp/controllers/AccountController.scala
app/uk/gov/hmrc/nisp/views/account.scala.html
app/uk/gov/hmrc/nisp/views/includes/fillGapsFutureProof.scala.html
conf/application.conf
conf/messages
test/resources/fillgaps-multiple/citizen-details.json
test/resources/fillgaps-multiple/nirecord.json
test/resources/fillgaps-multiple/summary.json
test/resources/fillgaps-singlegap/citizen-details.json
test/resources/fillgaps-singlegap/nirecord.json
test/resources/fillgaps-singlegap/summary.json
test/uk/gov/hmrc/nisp/controllers/AccountControllerSpec.scala
test/uk/gov/hmrc/nisp/controllers/FeedbackControllerSpec.scala
test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala
test/uk/gov/hmrc/nisp/helpers/MockAccountController.scala
test/uk/gov/hmrc/nisp/helpers/MockAuthConnector.scala
test/uk/gov/hmrc/nisp/helpers/MockBreadcrumb.scala
test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsHttp.scala
test/uk/gov/hmrc/nisp/helpers/MockExclusionController.scala
test/uk/gov/hmrc/nisp/helpers/MockNIRecordController.scala
test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala
test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala

* This PR future proofs the personal max information on the account page.
* As all years are not worth the same and may not add to their pension, we can no longer say "fill any year", "you only need to fill X years". So we have removed this information
* This does not apply if you literally only have one gap in your NI Record, so they will get the regular messaging
* I have added a feature switch as we don't need this to 2017
* As this is a feature switch, I have wrote the unit tests for both situations | @swaistle, @InduTest could you look at these and see if they are enough that we don't need acceptance tests?

NISP-2067: Future Proof Personal Max message

---

app/uk/gov/hmrc/nisp/connectors/CitizenDetailsConnector.scala
app/uk/gov/hmrc/nisp/connectors/NispConnector.scala
app/uk/gov/hmrc/nisp/controllers/AccountController.scala
app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala
app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala
app/uk/gov/hmrc/nisp/controllers/auth/AuthorisedForNisp.scala
app/uk/gov/hmrc/nisp/controllers/auth/NispUser.scala
app/uk/gov/hmrc/nisp/exceptions/EmptyPayeException.scala
app/uk/gov/hmrc/nisp/models/SPSummaryModel.scala
app/uk/gov/hmrc/nisp/models/citizen/Citizen.scala
app/uk/gov/hmrc/nisp/services/CitizenDetailsService.scala
app/uk/gov/hmrc/nisp/views/account.scala.html
app/uk/gov/hmrc/nisp/views/account_cope.scala.html
app/uk/gov/hmrc/nisp/views/account_cope_old.scala.html
app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html
app/uk/gov/hmrc/nisp/views/account_mqp.scala.html
app/uk/gov/hmrc/nisp/views/excluded_ni.scala.html
app/uk/gov/hmrc/nisp/views/excluded_sp_old.scala.html
app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala
test/uk/gov/hmrc/nisp/helpers/MockAuthConnector.scala
test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsHttp.scala
test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala
test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala

This PR at it's core switches the NINO in NispUser to `Nino` from the domain library instead of `Option[String]`. This will help enforce programmatically that the  service cannot work without a NINO on the user's account.
When the PAYE Account / NINO is pulled from the AuthContext a custom exception is now thrown instead.
I have also removed the use of `user.nino` in some of the views as it did nothing. If it needs to be there, it is available in the NispUser object.

NISP-2091: Enforce use of NINO type rather than String

---

app/uk/gov/hmrc/nisp/utils/Breadcrumb.scala
test/uk/gov/hmrc/nisp/utils/BreadcrumbSpec.scala

Also added further tests for this situation.
What I have done
- I have added a switch depending on whether the users' name is available. If it is, then the full breadcrumb is specified; if not, then the breadcrumb is missing the ```name``` parameter.
-Added 3 tests that check whether the breadcrumb url provided changes, based on whether users' name is empty or not.

NISP-2105 Added functionality to display breadcrumb when user's name is not available. 

---

package.json

To re-install the latest packages in your local machine, delete ``node_modules`` directory and run ``npm install``.

NISP-2110 Updating NPM packages to the latest versions

---

app/uk/gov/hmrc/nisp/controllers/AccountController.scala
app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala
app/uk/gov/hmrc/nisp/models/StatePension.scala
app/uk/gov/hmrc/nisp/services/StatePensionService.scala
app/uk/gov/hmrc/nisp/views/account_cope.scala.html
app/uk/gov/hmrc/nisp/views/account_cope_old.scala.html
test/uk/gov/hmrc/nisp/helpers/MockAccountController.scala
test/uk/gov/hmrc/nisp/models/StatePensionSpec.scala

- AccountController.showCope now uses `StatePensionService`
- Left copeTable functionality in for now, will need to be removed on nisp deconstruction
- Add a `contractedOut` boolean to the `StatePension` Model.
- Add a `StatePension` Model Spec
- Updated Exclusion Controller to properly use futures.

Refactor AccountController.showCope to use abstraction layer

---

app/uk/gov/hmrc/nisp/views/account.scala.html
test/uk/gov/hmrc/nisp/controllers/AccountControllerSpec.scala

This fixes the bug with the annual forecast amount being sent to GA rather than the weekly amount on the account page.
I've wrote unit tests for the account page.

NISP-2193: Fix bug with GA Dimensions

---

app/uk/gov/hmrc/nisp/views/account.scala.html
conf/messages

@Shaju-11 and @InduTest - I have removed:
- summary from messages 
- code from main page that displays the message (Continue and Continue with gaps scenarios)
@prashantchoudhari and @nehakannaujia - the code only has some deletions, so should be straightforward to check.

NISP-2257: Remove Summary

---

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss

font size of graph text is increased from .8em to 1 em for mobile devices.

NISP-1833: Graph font size change for Mobile device

---

app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html
conf/messages
test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala

@dspork, @prashantchoudhari and @nehadotkannaujia - just a minor amendment to the messages file.
@swaistle and @Shaju-11 - all ready to test

NISP-2379: Remove reference to State Pension age from Too Old Exclusion

---

app/uk/gov/hmrc/nisp/models/citizen/Citizen.scala
test/uk/gov/hmrc/nisp/models/CitizenDetailsResponseSpec.scala

This fixes the citizen details reader to parse both a Long and a Json Date. As citizen-details is in between schemas in different environments it makes sense to use both.

NISP-2414: Citizen Details Parser to use 2 schemas

---

app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html
conf/messages
conf/messages.cy
test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala

@swaistle and @Shaju-11 - the love @nehadotkannaujia has sorted out the unit tests on this one so should be simple and straightforward
@prashantchoudhari and @dspork - I have moved the URLs from the page to the messages file (as there are some Welsh versions of the pages they are going to)

NISP-2434: Remove URLS from VNICS page and move to messages

---

app/uk/gov/hmrc/nisp/models/NationalInsuranceRecord.scala
test/uk/gov/hmrc/nisp/controllers/NispFrontendControllerSpec.scala
test/uk/gov/hmrc/nisp/models/NationalnsuranceRecordSpec.scala

This is due to the bug https://github.com/hmrc/play-hal/issues/4.
This changes the JSON reads in NationalInsuranceRecord to read the tax years as an array unless it's a JsObject.

Parse TaxYears as JsArray and JsObject

---

app/uk/gov/hmrc/nisp/views/includes/deferral.scala.html
app/uk/gov/hmrc/nisp/views/statepension.scala.html
app/uk/gov/hmrc/nisp/views/statepension_forecastonly.scala.html
conf/messages
conf/messages.cy
test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala
test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala
test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala

DDCNLS-899: State Pension age is removed from deferral message and a new message has been added.
All unit tests passed.
@fred-jackson : Please review the content :-)
@dspork : please review code :-)
@Shaju-11  : Fred is happy with the changes(Check in jira ticket). Its ready to test.

DDCNLS-899: State Pension age is removed from deferral

---

app/uk/gov/hmrc/nisp/views/exclusions/ni/isleOfMan.scala.html

DDCNLS-900: Added UK national insurance message for isle of man NINO from PTA.
@dspork  : Please review its a one line change :-)
@fred-jackson  : Please review the content.

DDCNLS-900: IOM NI exclusion from PTA should mention UK NI record

---

LICENSE

When using the Apache License, it should not be modified. Individual copyrights notices should be supplied in the source code as stated in the APPENDIX (this has already been done).

 Use untouched Apache License

---

app/uk/gov/hmrc/nisp/views/includes/continueWorking.scala.html
app/uk/gov/hmrc/nisp/views/includes/reached.scala.html
app/uk/gov/hmrc/nisp/views/main.scala.html
app/uk/gov/hmrc/nisp/views/unauthenticatedMain.scala.html

Fixes the following HTML Validation errors which occur multiple times: 
Attribute “heading-bottom-margin” not allowed on element “h1” at this point.
Attribute “heading-bottom-margin” not allowed on element “h1” at this point.

Html validate CYSP
