hmrc/nisp-frontend

conf/messages
For consistency with all the other links, the icon has been added...
=> NISP-1533 Add new tab icon to link in IOM exclusion message

conf/messages
@swatcats143 and @dspork - all I've done is add nisp.nirecord.gap.underinvestigation to the messages file.
=> NISP-1445 Add account under investigation messaging to messages file

conf/messages
@swatcats143 - I've just added to the messages file so no need to test.
=> NISP-1539: Add C2 liability message to messages file

app/uk/gov/hmrc/nisp/models/NIRecordTaxYear.scala, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, test/resources/contractedout/nirecord.json, test/resources/excluded/nirecord.json, test/resources/fulluser/nirecord.json, test/resources/mqp/nirecord.json, test/resources/regular/nirecord.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala
https://github.com/hmrc/nisp/pull/7 needs merged before this can be used / tested.
=> NISP-1540: Added under investigation wording to NI Record

app/uk/gov/hmrc/nisp/assets/sass/nirecord.scss
Fixed. Minor changes in CSS. Tested in most desktop browsers.
=> NISP-1548 fixed bug with missing lines in IE8

app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/messages
@swatcats143 and @InduTest - I have ensured the correct message is displaying on this page.
=> NISP-1560: Ensure correct message displays on VNICs page

conf/messages
@swatcats143 and @InduTest 
Just a few edits: 
Remove unnecessary mentions of 'currently' from MQP messaging
Remove full stop from link only sentenc
=> NISP-1580: Minor edits to service

app/uk/gov/hmrc/nisp/views/excluded.scala.html
* Multiple exclusions are inserted as a comma separated value.
=> NISP-1579: Add exclusion type to GA dimension 20

app/uk/gov/hmrc/nisp/views/scenarios/guaranteePre2016.scala.html, app/uk/gov/hmrc/nisp/views/scenarios/guaranteeSpa.scala.html, conf/messages
* Merged both messages together as they are now the same.
* Left both scenario views, in case wording is changed again down the line
=> NISP-1606: Add new legal wording for both amounts

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss
Increased width to 780px since this is the breakpoint where the tabs are nominal
=> NISP-1612 Fixing bug with iPhone 6

app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/messages
@swatcats143 and @InduTest - HMRC wanted us to re-order the page so that you check what other State Pension bits n pieces you may get before seeking financial advice. Enjoy!
=> NISP-1623: Re-order sections

app/uk/gov/hmrc/nisp/views/exclusions/amountDissonance.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/dead.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/isleOfMan.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/mwrre.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/overseas.scala.html, conf/messages
@swatcats143 and @InduTest - let's try this again...
=> NISP-1621: Revised exclusion messages - IOM, Dissonance and MWRRE

app/uk/gov/hmrc/nisp/views/exclusions/spaBefore5April2016.scala.html, conf/messages
@swatcats143 and @InduTest - extra message added to the exclusion.
=> NISP-1639: Add contact FPC message to SPa before 5 April 2016 exclusion

app/uk/gov/hmrc/nisp/views/account.scala.html, conf/messages
@swatcats143 and @InduTest - revised messaging per the Jira ticket
=> NISP-1646: Implement recent COPE messaging changes

app/uk/gov/hmrc/nisp/views/scenarios/improveGapsDorothy.scala.html, app/uk/gov/hmrc/nisp/views/scenarios/improveGapsPriya.scala.html, app/uk/gov/hmrc/nisp/views/scenarios/improveWithGaps.scala.html, conf/messages
Removed dynamic number of gaps for Dorothy, Priya, Persephone, Tyrone and Susan. With @dspork
=> NISP-1582: Removed dynamic number of gaps on how to improve

app/uk/gov/hmrc/nisp/models/enums/SPExclusion.scala, app/uk/gov/hmrc/nisp/services/MetricsService.scala, app/uk/gov/hmrc/nisp/views/excluded.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/postStatePensionAge.scala.html, conf/messages
Added messages and views for the post State Pension age exclusion. With @dspork
=> NISP-1618: added post SP exclusion

app/uk/gov/hmrc/nisp/views/exclusions/postStatePensionAge.scala.html, conf/messages
@swatcats143 and @InduTest - I have just add _blank and (opens in new tab) to the last two links on this exclusion message.
=> NISP-1668: Post SPa exclusion

app/uk/gov/hmrc/nisp/views/exclusions/mwrre.scala.html, conf/messages
@swatcats143 and @InduTest: I have removed line 2, as it's not longer in use and I have removed the reference to line1 as it's erroneous.
=> NISP-1734: Update  MWRRE exclusion

conf/messages
@swatcats143 and @InduTest - I have re-targeted the URL to the new guidance page on GOV.UK. I have been asked to make sure there's a GA event on the link to the HTML fact sheet.
Over to you two!!!
=> NISP-1751: Retarget GOV.UK COPE URL

conf/messages
@swatcats143 and @InduTest - I have just updated the COPE message with an outstanding update from DWP legal/policy. ENJOY!!!
=> NISP-1626: Revised COPE messaging from DWP legal and policy

README.md
And you thought I wouldn't PR after I left!
=> Add master branch restriction to travis badge

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
* Fixed exception on NI record page when user does not have any tax years
* Removed pointless parameters on call to message
* I did this with @amyhart6
=> NISP-1764: Fixed bug with no NI record

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss
Also cleaned some CSS that are not needed.
=> NISP-1785 Fixed bug with extra visible line

app/uk/gov/hmrc/nisp/views/account.scala.html, app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html
@dspork and @InduTest - I have also replaced the hard-coded messages with HTML to the messages file.
=> NISP-1841: Remove erroneous full stop

app/uk/gov/hmrc/nisp/views/nirecordGapsAndHowToCheckThem.scala.html, app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/messages
@dspork and @InduTest - new messaging has been added to the following pages: 
- Check and correct
- Voluntary contributions
=> NISP-1779: Add post-IOM exclusion messages

conf/messages
@InduTest - just some minor changes
=> NISP-1869: Remove erroneous wording - to continue

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/models/SPSummaryModel.scala, app/uk/gov/hmrc/nisp/views/account.scala.html, app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/account_mqp.scala.html, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, app/uk/gov/hmrc/nisp/views/includes/abroad.scala.html, conf/messages, test/resources/abroad/citizen-details.json, test/resources/abroad/nirecord.json, test/resources/abroad/summary.json, test/resources/contractedout/summary.json, test/resources/excluded/summary.json, test/resources/forecastonly/summary.json, test/resources/invalidkey/summary.json, test/resources/mqp/summary.json, test/resources/mqp_abroad/citizen-details.json, test/resources/mqp_abroad/nirecord.json, test/resources/mqp_abroad/summary.json, test/resources/regular/summary.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/nisp/helpers/MockAuthConnector.scala, test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsHttp.scala, test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala, test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala
* Added isAbroad Boolean 
* Added abroad include file
* Added dynamic message to MQP, forecast only and regular users
* Added new overseas message
* Added abroad tests (regular user, MQP, forecast only user)
* Changed JSON summary files
* Updated NispConnectorSpec
* Added tests to AccountControllerTest
* Added mock user IDs and ninos
* With @fred-jackson
=> NISP-1791: Added overseas dynamic message.

app/uk/gov/hmrc/nisp/controllers/AccountController.scala, app/uk/gov/hmrc/nisp/models/SPForecastModel.scala, app/uk/gov/hmrc/nisp/views/account.scala.html, app/uk/gov/hmrc/nisp/views/includes/fillGaps.scala.html, app/uk/gov/hmrc/nisp/views/includes/fillGapsMQP.scala.html, app/uk/gov/hmrc/nisp/views/includes/spChart.scala.html, conf/messages, test/resources/contractedout/summary.json, test/resources/excluded/summary.json, test/resources/forecastonly/summary.json, test/resources/fulluser/summary.json, test/resources/mqp/summary.json, test/resources/regular/summary.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/AccountControllerSpec.scala
With @dspork 
Please do not merge this.
*** Testing is still pending.
=> NISP-1799: IFillgaps - miniman gaps scenarios for non-MQP customers

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/sp/amountDissonance.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/sp/isleOfMan.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/sp/overseas.scala.html, conf/messages
@InduTest - this one is pretty much good to go now (I am waiting to hear from Steve about the NI record from PTA exclusion, but we can always add a new story for that one).
=> NISP-1782 Revised IOM exclusion message

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, app/uk/gov/hmrc/nisp/views/exclusions/sp/mwrre.scala.html, conf/messages
@InduTest - all ready for you now my dear :smile:
=> NISP-1783: Add customer friendly MWRRE message

app/uk/gov/hmrc/nisp/connectors/NispConnector.scala, app/uk/gov/hmrc/nisp/controllers/AccountController.scala, app/uk/gov/hmrc/nisp/models/SPSummaryModel.scala, app/uk/gov/hmrc/nisp/models/enums/MQPScenario.scala, app/uk/gov/hmrc/nisp/views/account_mqp.scala.html, test/resources/abroad/summary.json, test/resources/contractedout/summary.json, test/resources/excluded/summary.json, test/resources/forecastonly/summary.json, test/resources/fulluser/summary.json, test/resources/invalidkey/summary.json, test/resources/mqp/summary.json, test/resources/mqp_abroad/summary.json, test/resources/regular/summary.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala
@dspork - Please review (think if we should use Scenarios at any more place?)
@InduTest - Please test
=> Nisp-1803: MQP Scenarios usage on Frontend

app/uk/gov/hmrc/nisp/controllers/AccountController.scala, app/uk/gov/hmrc/nisp/views/account_cope.scala.html, conf/messages
@InduTest - this just needs to be checked before it gets tested.
=> NISP-1885: Remove COPE table and replace with COPE estimate

app/uk/gov/hmrc/nisp/views/account.scala.html, app/uk/gov/hmrc/nisp/views/account_cope.scala.html, app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/account_mqp.scala.html, app/uk/gov/hmrc/nisp/views/excluded_ni.scala.html, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, app/uk/gov/hmrc/nisp/views/excluded_sp_old.scala.html, app/uk/gov/hmrc/nisp/views/main.scala.html, app/uk/gov/hmrc/nisp/views/nirecordGapsAndHowToCheckThem.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, public/javascript/app.js
Need to test on Staging to confirm, but so far it seems to fire off the events to GA. 
Also potentially we should discuss other ways of doing this, and merits of different approaches.
Take it away...
=> Nisp 1868 - Adding some event handling to register GA event for clicking on breadcrumbs

app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, conf/messages
@InduTest - I've added reference to SP for paper statements; Added UK to IOM NI record statement message only
@dspork - I've added some logic in the exclusion message to identify if they are IOM or not.
=> NISP-1912: Revised IOM exclusion message

app/uk/gov/hmrc/nisp/utils/Constants.scala, app/uk/gov/hmrc/nisp/views/account.scala.html, app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/includes/deferral.scala.html, app/uk/gov/hmrc/nisp/views/includes/fillGapsMQP.scala.html, conf/messages
@InduTest - Create deferral include; Add deferral cut off age constant; Added include to Account.Scala and Account_Forecastonly.Scala
@dspork - Added so that @InduTest can start on the tests, but there may need to be more changes before it's finished.
=> NISP-1324: Adding deferral message when users are at least 54 years old

app/uk/gov/hmrc/nisp/views/account.scala.html
To be used for statistical usage
=> NISP-1860 Added Dimension 40 that contains the age of the user

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss, app/uk/gov/hmrc/nisp/controllers/QuestionnaireController.scala, app/uk/gov/hmrc/nisp/events/QuestionnaireEvent.scala, app/uk/gov/hmrc/nisp/models/forms/QuestionnaireForm.scala, app/uk/gov/hmrc/nisp/views/includes/input.scala.html, app/uk/gov/hmrc/nisp/views/includes/questionnaireForm.scala.html, conf/messages, project/FrontendBuild.scala, public/javascript/app.js, test/uk/gov/hmrc/nisp/controllers/QuestionnaireControllerSpec.scala, test/uk/gov/hmrc/nisp/events/QuestionnaireEventSpec.scala
- Uses Jquery to display/hide depending on the answer
- script only loads if the questionnaire component is loaded
- bumped questionnaire version to 6
=> Nisp 1915 - Added question for research with email address

conf/messages
@dspork - pretty sure this will be okay for next sprint...
@InduTest and @swaistle - not sure that you'll need to do tests on this one!
=> NISP-1962: Remove extra space

app/uk/gov/hmrc/nisp/utils/Constants.scala, conf/application.conf, conf/prod.routes, test/uk/gov/hmrc/nisp/controllers/AccountControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/QuestionnaireControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/RedirectControllerSpec.scala
The new url should be working Ok, and all tests are green.
=> Nisp:1828 Changing the service URL to /check-your-state-pension

conf/messages
@dspork and @prashantchoudhari - messages file updated
@swaistle and @InduTest - all ready to test (take care, there is a present and a past version of the overseas message)
=> NISP-2008: Revise overseas message

app/uk/gov/hmrc/nisp/views/account_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/account_mqp.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages
@dspork and @prashantchoudhari - I've also included some nowrap spans
@swaistle and @InduTest - this should be ready to test, but I couldn't do the NI summary as there is a div with it's own class that is probably mucking things up for me. We may need to ask @gussoo and @roundrobin99 to have a look at this if you need this completed as well.
=> NISP-2009: Add 5 April to current amount and NI summary

conf/messages
@dspork and @prashantchoudhari - only replaced a few words in the messages file
@swaistle and @InduTest - all done ready to test
=> NISP-2019: Replace increase with improve - in relation to SP amount only

app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyearNoFull.scala.html, conf/messages
=> NISP-2025: Changed NI credits message layout

app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/models/NISummary.scala, app/uk/gov/hmrc/nisp/views/nirecordGapsAndHowToCheckThem.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, test/resources/abroad/nirecord.json, test/resources/contractedout/nirecord.json, test/resources/forecastonly/nirecord.json, test/resources/fulluser/nirecord.json, test/resources/homeresponsibilitiesprotection/citizen-details.json, test/resources/homeresponsibilitiesprotection/nirecord.json, test/resources/homeresponsibilitiesprotection/summary.json, test/resources/mqp_abroad/nirecord.json, test/resources/regular/nirecord.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/helpers/MockAuthConnector.scala, test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsHttp.scala, test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala, test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala
* created hrp test user
* added homeResponsibilitiesProtection to all existing nirecord.json files
* unit tests written
* needs backend pull request merged first
=> NISP-2037: added HRP message and functionality to front end

app/uk/gov/hmrc/nisp/connectors/NispConnector.scala, app/uk/gov/hmrc/nisp/controllers/AccountController.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/controllers/QuestionnaireController.scala, test/resources/invalidkey/nirecord.json, test/uk/gov/hmrc/nisp/connectors/NispConnectorSpec.scala
* This removes the squashing of errors in the NispConnector
* Also removing the redundant use of async in the QuestionnaireController.
=> NISP-2055: Refactor error handling

public/javascript/app.js
Removed 2 console-log debug outputs as not needed.
=> NISP-2082 Removed console.log debug output messages

app/uk/gov/hmrc/nisp/connectors/CitizenDetailsConnector.scala, app/uk/gov/hmrc/nisp/connectors/IdentityVerificationConnector.scala, app/uk/gov/hmrc/nisp/connectors/NispConnector.scala, app/uk/gov/hmrc/nisp/controllers/AccountController.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/controllers/pertax/PertaxHelper.scala, app/uk/gov/hmrc/nisp/services/MetricsService.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/helpers/MockAccountController.scala, test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsService.scala, test/uk/gov/hmrc/nisp/helpers/MockIdentityVerificationConnector.scala, test/uk/gov/hmrc/nisp/helpers/MockMetricsService.scala, test/uk/gov/hmrc/nisp/helpers/MockNIRecordController.scala, test/uk/gov/hmrc/nisp/helpers/MockNispConnector.scala
* Added Metrics trait and refactored code to use it
* Changed "cacheFuture" to "cacheF" in PertaxHelper.
* with @amyhart6
=> NISP-1752: Abstract Metrics into Trait

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss, app/uk/gov/hmrc/nisp/views/exclusions/viewExclusions.scala.html
Removed redundant html from the "viewExlusions" page
Removed redundant style from "nisp.scss"
=> NISP 2103 Removed styling for 'dead' messaging

app/uk/gov/hmrc/nisp/views/includes/continueWorking.scala.html, conf/messages
Changed messaging for will reach scenarios to now have messaging from have reached and MQP may/never.
=> Consistency of wording around continuing to pay NI/pay until SPA

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/views/excluded_dead.scala.html, app/uk/gov/hmrc/nisp/views/excluded_ni.scala.html, conf/messages, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala
* Made Dead have priority over MCI just like SP Exclusion Page
* Added regular exclusion priority (IOM over MWRRE)
* Dead and MCI pages are now shared completely
* Age is not passed to GA when NI Exclusion
=> NISP-2104: Revise NI Exclusions

app/uk/gov/hmrc/nisp/views/account_mqp.scala.html, conf/messages
@swaistle and @Shaju-11 - I have pushed this (just one paragraph has been taken out - completely)
@prashantchoudhari - just the one paragraph has been removed.
=> NISP-2261: Remove Pension Tracing signpost from MQP may/never

conf/messages
@Shaju-11 and @InduTest - all ready to test (reached and forecast only)
@prashantchoudhari and @nehakannaujia - very minor amendment to messages
=> NISP-2256: Align message with paper statement

conf/messages
Changed lockout message from 7 days to 24 hours.
=> NISP-2299: Changed the lockout message for 24 hours.

conf/messages
@swaistle and @Shaju-11 - update made and ready to test
=> NISP-2319: Revise Verify set-up duration

app/uk/gov/hmrc/nisp/assets/sass/nisp.scss, app/uk/gov/hmrc/nisp/views/main.scala.html
Fixed : Space between the two headings is increased for mobile devices.
=> NISP-2337 : Increased space between Your state pension and summary heading

app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/messages, test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala
Added unit tests for Voluntary contribution view
=> NISP-2369: Unit tests for 'Voluntary contribution' view

test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala
NISP-2369 : Added unit tests for Voluntary contribution view
=> NISP-2369 : Unit tests for Voluntary Contribution

test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala
NISP-2369 : Removed Controller object as not being used
=> NISP-2369 : Fixed the compile issue after refactor merge

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/events/AccountExclusionEvent.scala, app/uk/gov/hmrc/nisp/models/StatePensionExclusionFiltered.scala, app/uk/gov/hmrc/nisp/services/StatePensionService.scala, app/uk/gov/hmrc/nisp/views/excluded_dead.scala.html, app/uk/gov/hmrc/nisp/views/excluded_mci.scala.html, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, test/uk/gov/hmrc/nisp/services/StatePensionServiceSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala
Changes so there is only one exclusion sent to Google Analytics / the frontend views
=> NISP-2363: Change GA exclusions to be single

app/uk/gov/hmrc/nisp/views/includes/questionnaireSidebar.scala.html, conf/messages, test/uk/gov/hmrc/nisp/views/FormsViewSpec.scala, test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala, test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala
Added unit tests for Questionnaire form.
Added all the methods for HTMLView
@dspork  : Please review :-)
=> NISP-2382 : Unit tests for Questionnaire Form 

conf/messages
@nehadotkannaujia - I have gone through and deleted them. All ready to test - EEK
@swaistle and @Shaju-11 - all ready for you guys now
=> NISP-2385: Remove erroneous messages

test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala
NISP-2366 : Completed and verified Unit tests for COPE.
@dspork  : Please review :-)
=> NISP-2366 : Unit tests for State Pension COPE scenario

app/uk/gov/hmrc/nisp/views/main.scala.html, conf/messages
@nehadotkannaujia and @dspork - I have put the sign-out wording into the messages file
@swaistle and @Shaju-11 - not sure how this will affect your tests.
=> NISP-2386: Replace hard-coded messaging

conf/messages.cy, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
NISP-2387 : Welsh language implementation is done. All the unit tests have passed .
@dspork  Please review :-)
=> NISP-2387 : Welsh Language implementation 

app/uk/gov/hmrc/nisp/views/includes/language_selection.scala.html, app/uk/gov/hmrc/nisp/views/main.scala.html, test/uk/gov/hmrc/nisp/views/LanguageSelectionSpec.scala
@prashantchoudhari  and @dspork  : Please review.
=> NISP-2418 : Added Google Analytics for language toggle

conf/messages
@swaistle and @Shaju-11 - I have run unit test thingys and it looks okay. This is in the next sprint, so there's absolutely no rush.
@dspork, @prashantchoudhari and @nehakannaujia - I have just removed a full stop...
=> NISP-2397: Remove full stop from heading

app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, conf/messages, conf/messages.cy
@swaistle and @Shaju-11 - all ready to test (just text changes so shouldn't affect anything)
@dspork, @nehadotkannaujia and @prashantchoudhari - all ready for the code to be checked, should be straightforward enough.
=> NISP-2432: Revise Welsh translation with Welsh Translation Unit team

app/assets/stylesheets/nisp.scss, app/uk/gov/hmrc/nisp/controllers/CustomLanguageController.scala, conf/app.routes, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala
NISP-2443 : Welsh landing page implemented
@dspork  : Please review.
=> NISP-2443 : Welsh landing page 

app/assets/stylesheets/nisp.scss
NISP-2444 : Code changes to make Welsh text visible in Graph.
@dspork  Please review.
=> NISP-2444 : Css changes for Welsh text in graph

app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/views/includes/fillGaps.scala.html, app/uk/gov/hmrc/nisp/views/includes/fillGapsFutureProof.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala
NISP-2260: Changed wordings for personal max scenario.
@dspork : Please review.
=> NISP-2260: Changed wordings for personal max scenario

app/uk/gov/hmrc/nisp/connectors/BackendConnector.scala, app/uk/gov/hmrc/nisp/utils/JsonDepersonaliser.scala, test/uk/gov/hmrc/nisp/connectors/BackendConnectorSpec.scala, test/uk/gov/hmrc/nisp/utils/JsonDepersonaliserSpec.scala
All unit tests passing and manually tested against other services
=> NISP-2442: depersonalise NI record JSON for debugging

app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/controllers/NispFrontendController.scala, app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, test/resources/backend-not-found/citizen-details.json, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NispFrontendControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/helpers/MockAuthConnector.scala, test/uk/gov/hmrc/nisp/helpers/MockCitizenDetailsHttp.scala, test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala, test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala
All unit tests passing and running with other services
=> NISP-2093: Use generic error page for backend 404

project/FrontendBuild.scala
Part of Inter-Microservice Domain Configuration
Only needed to upgrade bootstrap in this project
=> DDCNLS-897: upgrade bootstrap version

project/plugins.sbt
Upgraded Play to 2.5.12 to hopefully fix memory leak in frontend
=> DDCNLS-945: upgraded Play to 2.5.12

app/uk/gov/hmrc/nisp/views/includes/contractedOut.scala.html, app/uk/gov/hmrc/nisp/views/statepension_cope.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala
DDCNLS-901: Restructured COPE page to align with paper statement for both English and Welsh. All the unit tests passed.
@fred-jackson  : Please review page content :-)
@dspork : Please review code :-)
@Shaju-11: Once reviewed and approved, you can start testing, i will update the ticket status :-)
=> DDCNLS-901:Restructure COPE page to align with paper statement

conf/messages, conf/messages.cy
DDCNLS-901: Moved full stop outside of link
@swaistle  : Its done and Unit tests passed. Please test and merge if happy with the changes :-)
=> DDCNLS-901: Moved full stop outside of link

app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala
DDCNLS-903 : Revised voluntary contribution page. All unit tests passed.
@dspork : Please review :-)
@Shaju-11 : Once approved, ready to test :-)
=> DDCNLS-903 : Revised voluntary contribution page

test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
DDCNSLS-1210 : Removd Get help with URL unit tests to check
=> DDCNSLS-1210 : Removd Get help with URL unit tests to check

conf/messages, conf/messages.cy
DDCNLS-1214 : Changed page headings and title for NISP.
=> DDCNLS-1214 : Changed page headings and title for NISP.

conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/TermsConditionsControllerSpec.scala
DDCNLS-1216 : Content changes for T&C
=> DDCNLS-1216 : Content changes for t&c

conf/messages, conf/messages.cy
DDCNLS-1215 : Changed content for gaps and cost of filling them link
=> DDCNLS-1215 : Changed content for gaps and cost of filling them link

app/uk/gov/hmrc/nisp/views/excluded_mci.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala
DDCNLS-1222: Changed content for MCI Exclusion
=> DDCNLS-1222: Changed content for MCI Exclusion

app/assets/javascript/nirecord.js, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
DDCNLS-1202: Accessibility Expand and collapse link. Created pull req to test the changes on actual device before releasing it to testing.
=> DDCNLS-1202: Accessibility Expand and collapse link

project/build.properties
DDCNLS-1362: Updated sbt version
=> DDCNLS-1362: Updated sbt version

app/uk/gov/hmrc/nisp/views/exclusions/dead.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala
DDCNLS:1292: Added call center opening hours
=> DDCNLS:1292: Added call center opening hours

app/uk/gov/hmrc/nisp/views/statepension.scala.html, app/uk/gov/hmrc/nisp/views/statepension_mqp.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
DDCNLS-1581 : NISP leagal caveats
=> DDCNLS-1581 : NISP leagal caveats

app/uk/gov/hmrc/nisp/views/statepension.scala.html, app/uk/gov/hmrc/nisp/views/statepension_cope.scala.html, app/uk/gov/hmrc/nisp/views/statepension_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/statepension_mqp.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
DDCNLS-1291: Added Textphone to sidebar help.
=> DDCNLS-1291: Added Textphone to sidebar help

conf/messages.cy
DDCNLS-1291: Change 8am to 6pm to 8am i 6pm for welsh.
=> DDCNLS-1291: Change 8am to 6pm to 8am i 6pm for welsh

app/assets/stylesheets/nisp.scss, app/uk/gov/hmrc/nisp/views/nirecordGapsAndHowToCheckThem.scala.html, app/uk/gov/hmrc/nisp/views/nirecordVoluntaryContributions.scala.html, conf/application.conf
DDCNLS-1154: Firefox arrow issue fixed
=> DDCNLS-1154: Firefox arrow issue fixed

app/uk/gov/hmrc/nisp/views/main.scala.html, app/uk/gov/hmrc/nisp/views/questionnaire.scala.html
DDCNLS-1920: Added welsh language and last login.
=> DDCNLS-1920: Added welsh language and last login

conf/messages.cy, test/uk/gov/hmrc/nisp/helpers/MockBreadcrumb.scala, test/uk/gov/hmrc/nisp/helpers/MockExclusionController.scala, test/uk/gov/hmrc/nisp/helpers/MockNIRecordController.scala, test/uk/gov/hmrc/nisp/helpers/MockStatePensionController.scala, test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala, test/uk/gov/hmrc/nisp/views/QuestionnaireFormViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewWelshSpec.scala, test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewSpec.scala, test/uk/gov/hmrc/nisp/views/VoluntaryContributionsViewWelshSpec.scala
Includes new Welsh language unit tests for all existing View unit tests.
=> CYSPA-51 - State Pension Age Under Consideration message - Welsh language version

app/assets/stylesheets/_nirecord.scss, app/assets/stylesheets/nisp.scss, app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/views/includes/questionnaireForm.scala.html, app/uk/gov/hmrc/nisp/views/main.scala.html, app/uk/gov/hmrc/nisp/views/statepension.scala.html, app/uk/gov/hmrc/nisp/views/statepension_forecastonly.scala.html, conf/application.conf, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala
DDCNLS-2633': Taas asset frontend version upgrade.
=> PLEASE DO NOT MERGE : DDCNLS-2633': Taas asset frontend version upgrade

conf/application.conf
DDCNLS-2884: Upgraded Asset frontend version to 3.2.2
=> DDCNLS-2884: Upgraded Asset frontend version to 3.2.2

project/FrontendBuild.scala, test/uk/gov/hmrc/nisp/views/QuestionnairFormViewSpec.scala
DDCNLS-3036 : Upgraded bootstap library
=> DDCNLS-3036 : Upgraded bootstap library

app/uk/gov/hmrc/nisp/views/main.scala.html, conf/messages
Don't merge until the Optimizely campaign has been tested and deployed to production.
=> DDCNLS-3078 Set up and run A/B test for CySP's user panel banner

conf/messages
@kurtlogan - I've only replaced the URL (as requested by Comms). Unit tests are okay.
=> DDCNLS-4846: Replace YourPension URL for Comms

conf/messages
Reverts hmrc/nisp-frontend#342
=> Revert "DDCNOS-2311: Updated UR banner link from AB test to cysp campaign"

conf/messages
Reverts hmrc/nisp-frontend#343
=> DDCNOS-2311: Updated UR banner link from AB test to cysp campaign

app/uk/gov/hmrc/nisp/utils/Constants.scala, test/uk/gov/hmrc/nisp/controllers/auth/AuthDetailsSpec.scala
Changed provider type id to match responses from auth
=> Verify hotfix

conf/application.conf
=> iv-stubFix: The URL and IDs have changed for the iv uplift

app/uk/gov/hmrc/nisp/views/includes/attorneyBanner.scala.html, app/uk/gov/hmrc/nisp/views/main.scala.html, conf/app.routes, project/AppDependencies.scala
=> DDCNL-4759 Added in support for FANDF attorneyBanner

app/uk/gov/hmrc/nisp/controllers/auth/AuthAction.scala, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala
=> removed unused imports

app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/models/StatePensionExclusionFiltered.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala
=> Ddcnl 6004

app/uk/gov/hmrc/nisp/connectors/BackendConnector.scala, app/uk/gov/hmrc/nisp/connectors/StatePensionConnector.scala, app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/controllers/pertax/PertaxHelper.scala, app/uk/gov/hmrc/nisp/services/StatePensionService.scala, it/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/services/StatePensionServiceSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
=> Ddcnl 6271

conf/messages, conf/messages.cy
=> [DDCNL-6441] Update DWP Opening Hours

app/uk/gov/hmrc/nisp/services/NationalInsuranceService.scala, it/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnectorImplSpec.scala, test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/services/StatePensionServiceSpec.scala
=> Ddcnl 6101

project/plugins.sbt
=> DDCNL-6750: updated play plugin version

app/uk/gov/hmrc/nisp/connectors/BackendConnector.scala, it/controllers/ExclusionControllerISpec.scala, it/controllers/LandingControllerISpec.scala, it/controllers/NIRecordControllerISpec.scala, it/controllers/RedirectControllerISpec.scala, it/controllers/StatePensionControllerISpec.scala, it/controllers/TermsConditionsControllerISpec.scala, project/build.properties
=> [DDCNL-6812] Increasing IT test coverage

app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/models/StatePensionExclusion.scala, app/uk/gov/hmrc/nisp/utils/JsonDepersonaliser.scala, app/uk/gov/hmrc/nisp/views/includes/continueWorking.scala.html, app/uk/gov/hmrc/nisp/views/includes/newComponents/Panel.scala.html, app/uk/gov/hmrc/nisp/views/includes/reached.scala.html, app/uk/gov/hmrc/nisp/views/statepension.scala.html, app/uk/gov/hmrc/nisp/views/statepension_forecastonly.scala.html, build.sbt, conf/app.routes, project/AppDependencies.scala, test/uk/gov/hmrc/nisp/connectors/CitizenDetailsConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/IdentityVerificationConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnectorImplSpec.scala, test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/auth/AuthActionSpec.scala, test/uk/gov/hmrc/nisp/helpers/MockNispHttp.scala, test/uk/gov/hmrc/nisp/helpers/TestAccountBuilder.scala, test/uk/gov/hmrc/nisp/messages/MessagesSpec.scala, test/uk/gov/hmrc/nisp/models/StatePensionExclusionSpec.scala, test/uk/gov/hmrc/nisp/services/CitizenDetailsServiceSpec.scala, test/uk/gov/hmrc/nisp/services/NationalInsuranceServiceSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
=> Ddcnl 6852

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/views/service_error_500.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/errorHandler/ErrorHandlerSpec.scala
=> DDCNL-7054 Created Excessive Traffic Toggle

conf/application.conf
=> DDCNL-Traffic-Toggle-Off

conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
=> Upgrade libraries

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> [DDCNL-7273] Notification Banner for new CYSP Deadline

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/errorHandler/ErrorHandler.scala, app/uk/gov/hmrc/nisp/models/admin/FeatureFlag.scala, app/uk/gov/hmrc/nisp/repositories/admin/FeatureFlagRepository.scala, app/uk/gov/hmrc/nisp/views/service_error_500.scala.html, conf/app.routes, conf/application.conf, conf/prod.routes, test/uk/gov/hmrc/nisp/errorHandler/ErrorHandlerSpec.scala, test/uk/gov/hmrc/nisp/models/admin/FeatureFlagSpec.scala
=> DDCNL-7091 Added Traffic Toggle

conf/messages, conf/messages.cy
=> [DM] [NI-DATE-UPDATE] Update the dates for the ni contributions deadline

app/uk/gov/hmrc/nisp/controllers/TimeoutController.scala, app/uk/gov/hmrc/nisp/views/main.scala.html, conf/app.routes, conf/application.conf, test/uk/gov/hmrc/nisp/controllers/TimeoutControllerSpec.scala
=> DDCNL-6977: Adding service timeout dialog box

it/connectors/StatePensionConnectorSpec.scala, it/controllers/ExclusionControllerISpec.scala, it/controllers/LandingControllerISpec.scala, it/controllers/NIRecordControllerISpec.scala, it/controllers/RedirectControllerISpec.scala, it/controllers/StatePensionControllerISpec.scala, it/controllers/TermsConditionsControllerISpec.scala, it/it_utils/WiremockHelper.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/services/NationalInsuranceServiceSpec.scala, test/uk/gov/hmrc/nisp/utils/UnitSpec.scala
=> Ddcnl 7570

app/assets/stylesheets/nisp.scss
=> DDCNL-6979: fixing clipped text

app/uk/gov/hmrc/nisp/views/Main.scala, app/uk/gov/hmrc/nisp/views/identity_verification_landing.scala.html, app/uk/gov/hmrc/nisp/views/statepension.scala.html, app/uk/gov/hmrc/nisp/views/statepension_forecastonly.scala.html, app/uk/gov/hmrc/nisp/views/statepension_mqp.scala.html, project/AppDependencies.scala, test/uk/gov/hmrc/nisp/views/MainViewSpec.scala
=> [DM] [SCA_WRAPPER_V_BUMP] Updated SCA_Wrapper and some GOVUK stuff as a consequence

app/uk/gov/hmrc/nisp/views/Main.scala, app/uk/gov/hmrc/nisp/views/identity_verification_landing.scala.html, app/uk/gov/hmrc/nisp/views/oldMain.scala.html, conf/application.conf
=> [DM] [SCA_WRAPPER_V_BUMP] Minor fixes

app/uk/gov/hmrc/nisp/views/Main.scala, app/uk/gov/hmrc/nisp/views/oldMain.scala.html, project/AppDependencies.scala, test/uk/gov/hmrc/nisp/views/MainViewSpec.scala
=> [DM] [TIMEOUT_URL_ADDITION] Added timeout url to layout

app/uk/gov/hmrc/nisp/connectors/BackendConnector.scala, app/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnector.scala, app/uk/gov/hmrc/nisp/services/NationalInsuranceService.scala, it/connectors/NationalInsuranceConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/services/NationalInsuranceServiceSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
=> Ddcnl 7723

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> Ddcnl 7737

app/uk/gov/hmrc/nisp/connectors/BackendConnector.scala, app/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnector.scala, app/uk/gov/hmrc/nisp/connectors/StatePensionConnector.scala, app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/services/NationalInsuranceService.scala, app/uk/gov/hmrc/nisp/services/StatePensionService.scala, it/connectors/NationalInsuranceConnectorSpec.scala, it/connectors/StatePensionConnectorSpec.scala, it/controllers/ExclusionControllerISpec.scala, it/controllers/NIRecordControllerISpec.scala, it/controllers/StatePensionControllerISpec.scala, it/it_utils/WiremockHelper.scala, test/uk/gov/hmrc/nisp/connectors/BackendConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/NationalInsuranceConnectorSpec.scala, test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/ExclusionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/services/NationalInsuranceServiceSpec.scala, test/uk/gov/hmrc/nisp/services/StatePensionServiceSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala
=> Ddcnl 7898

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> [DDCNL-8001] Update Nirecord page title

project/AppDependencies.scala
=> DDCNL-8076 updated Mongo feature toggle client

app/uk/gov/hmrc/nisp/controllers/auth/PertaxAuthAction.scala, conf/logback.xml, it/controllers/StatePensionControllerISpec.scala
=> [DM] [PertaxAuthHeaderUpdate] Updated hc down to pertax

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> DDCNL-8375 updated banner

conf/messages, conf/messages.cy
=> DDCNL-8375: updated NI banner with Welsh

conf/logback.xml, project/plugins.sbt
=> DDCNL-8114 Added colour logging

conf/messages, conf/messages.cy
=> [DDCNL-8395] Tweaks for uprating scenario messages

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/config/ApplicationStartUp.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/models/admin/FeatureFlags.scala, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> Add button to view payable gaps in nisp-modelling-fe

app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/events/NIRecordNoGapsEvent.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala
=> Ddcnl 8788

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, conf/application.conf
=> Fix URL for nisp-modelling-journey

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala
=> Ddcnl 8443 - add button to full ni record view

app/assets/stylesheets/_nirecord.scss, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> DDCNL 8821 & DDCN 8830

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> DDCNL-8923 remove blue you can soon pay VNIC banner

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/views/Main.scala, app/uk/gov/hmrc/nisp/views/excluded_ni.scala.html, app/uk/gov/hmrc/nisp/views/excluded_sp.scala.html, conf/application.conf, test/resources/application.conf, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/TermsConditionsControllerSpec.scala, test/uk/gov/hmrc/nisp/errorHandler/ErrorHandlerSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeFailedNIViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeFailedSPViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeNIViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeSPViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionViewSpec.scala, test/uk/gov/hmrc/nisp/views/MainViewSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala, test/uk/gov/hmrc/nisp/views/TermsAndConditionsViewSpec.scala
=> Ddcnl 8910

app/uk/gov/hmrc/nisp/connectors/PertaxAuthConnector.scala, test/uk/gov/hmrc/nisp/utils/PertaxAuthMockingHelper.scala
=> Updated the URL for the deceased partial

app/uk/gov/hmrc/nisp/views/includes/contractedOut.scala.html
=> DDCNL-9087: changed cope link

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages
=> [DM] [DDCNL-9153] Added a notice banner

conf/messages.cy
=> [DM] [DDCNL-9153] Added key to Welsh so tests pass

app/uk/gov/hmrc/nisp/controllers/pertax/PertaxHelper.scala, app/uk/gov/hmrc/nisp/repositories/SessionCacheRepository.scala, it/test/uk/gov/hmrc/nisp/repositories/SessionCacheNewSpec.scala, test/uk/gov/hmrc/nisp/connectors/IdentityVerificationConnectorSpec.scala, test/uk/gov/hmrc/nisp/controllers/pertax/PertaxHelperSpec.scala
=> DDCNL-9003: migrate from http caching

conf/messages, conf/messages.cy
=> DDCNL-9154 added welsh to nirecord.banner

app/uk/gov/hmrc/nisp/controllers/ExclusionController.scala, app/uk/gov/hmrc/nisp/controllers/auth/AuthRetrievals.scala, app/uk/gov/hmrc/nisp/errorHandler/ErrorHandler.scala, app/uk/gov/hmrc/nisp/views/Main.scala, app/uk/gov/hmrc/nisp/views/global_error.scala.html, build.sbt, conf/application.conf, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/resources/logback-test.xml, test/uk/gov/hmrc/nisp/controllers/auth/AuthRetrievalsSpec.scala, test/uk/gov/hmrc/nisp/controllers/auth/PertaxAuthActionSpec.scala, test/uk/gov/hmrc/nisp/errorHandler/ErrorHandlerSpec.scala, test/uk/gov/hmrc/nisp/views/MainViewSpec.scala
=> DDCNL-9118: update SCA wrapper

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy
=> DDCNL-9240 remove delay banner

app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyearNoFull.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> DDCNL-9271 Fixed View Payable Gaps button on /nirecord page

app/uk/gov/hmrc/nisp/connectors/StatePensionConnector.scala, it/test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala, it/test/uk/gov/hmrc/nisp/controllers/ExclusionControllerISpec.scala, it/test/uk/gov/hmrc/nisp/controllers/NIRecordControllerISpec.scala, it/test/uk/gov/hmrc/nisp/controllers/StatePensionControllerISpec.scala, test/uk/gov/hmrc/nisp/connectors/StatePensionConnectorSpec.scala
=> DDCNL-9575: call state-pension pertax authorised endpoint

conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/statePension/StatePensionMQPViewSpec.scala
=> DDCNL-9228: Amended copy

app/assets/stylesheets/nisp.scss, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
=> Only display the button if there are payable gaps

app/uk/gov/hmrc/nisp/views/statePension/StatePensionCopeView.scala.html, app/uk/gov/hmrc/nisp/views/statePension/StatePensionForecastOnlyView.scala.html, app/uk/gov/hmrc/nisp/views/statePension/StatePensionMqpView.scala.html, app/uk/gov/hmrc/nisp/views/statePension/StatePensionView.scala.html, test/uk/gov/hmrc/nisp/views/statePension/StatePensionCopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionForecastOnlyViewSpec.scala
=> DDCNL-9229 | Remove 'which-view' p tags

conf/messages
=> DDCNL-10115: Updated VNICs year

app/assets/javascript/app.js, app/assets/stylesheets/nisp.scss
=> Fix border not shown issue

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/models/PayableGapExtensionDetails.scala, app/uk/gov/hmrc/nisp/models/PayableGapExtensionStatus.scala, app/uk/gov/hmrc/nisp/models/PayableGapInfo.scala, app/uk/gov/hmrc/nisp/services/NIPayGapExtensionService.scala, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/config/ApplicationConfigSpec.scala, test/uk/gov/hmrc/nisp/controllers/LandingControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/NIRecordControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/TermsConditionsControllerSpec.scala, test/uk/gov/hmrc/nisp/controllers/auth/AuthRetrievalsSpec.scala, test/uk/gov/hmrc/nisp/controllers/auth/ExcludedAuthActionSpec.scala, test/uk/gov/hmrc/nisp/errorHandler/ErrorHandlerSpec.scala, test/uk/gov/hmrc/nisp/services/NIPayGapExtensionServiceSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeFailedNIViewSpec.scala, test/uk/gov/hmrc/nisp/views/ExclusionCopeFailedSPViewSpec.scala, test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePensionViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_CopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/StatePension_MQPViewSpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionCopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionForecastOnlyViewSpec.scala
=> Ddcnl 10237

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/services/NIPayGapExtensionService.scala, conf/application.conf, conf/messages, conf/messages.cy
=> DDCNL-10237: update Future Pension Centre contact numbers

conf/application.conf
=> DDCNL-10237: config update

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/messages, conf/messages.cy
=> DDCNL-10237: update to pension summary view text

app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html
=> DDCNL-10393: show grace period banner to all

conf/messages.cy
=> DDCNL-10393: added welsh translation

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, conf/application.conf, project/AppDependencies.scala, test/uk/gov/hmrc/nisp/controllers/StatePensionControllerSpec.scala
=> DDCNL-10707 | Update sign-out to use bas-gateway URL

app/uk/gov/hmrc/nisp/controllers/StatePensionController.scala, app/uk/gov/hmrc/nisp/views/statePension/StatePensionCopeView.scala.html, conf/app.routes, it/test/uk/gov/hmrc/nisp/controllers/StatePensionControllerISpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionCopeViewSpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionMQPViewSpec.scala, test/uk/gov/hmrc/nisp/views/statePension/StatePensionViewSpec.scala
=> DDCNL-10768 | Create separate routes for new CYSP UI

app/uk/gov/hmrc/nisp/views/includes/statePension/continueWorking.scala.html, app/uk/gov/hmrc/nisp/views/includes/statePension/reached.scala.html, conf/messages, conf/messages.cy, project/AppDependencies.scala, project/plugins.sbt, test/uk/gov/hmrc/nisp/views/statePension/StatePensionViewSpec.scala
=> DDCNL-10162 | CYSP summary: content change for personal max bar chart (no gaps)

app/uk/gov/hmrc/nisp/config/ApplicationConfig.scala, app/uk/gov/hmrc/nisp/controllers/NIRecordController.scala, app/uk/gov/hmrc/nisp/services/FandFService.scala, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyear.scala.html, app/uk/gov/hmrc/nisp/views/includes/nirecordtaxyearNoFull.scala.html, app/uk/gov/hmrc/nisp/views/nirecordpage.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/uk/gov/hmrc/nisp/views/HtmlSpec.scala, test/uk/gov/hmrc/nisp/views/NIRecordViewSpec.scala
=> DDCNL-8700: change to NI Record page
